# Starship Prompt Configuration
# Auto-synced with Quickshell Theme: 

format = """[](bg:#b8bb26 fg:#282828)[󰣇 ](bg:#282828 fg:#b8bb26)[](fg:#282828 bg:#3c3836)$time[](fg:#3c3836 bg:#282828)$directory[](fg:#282828 bg:#282828)$git_branch$git_status$git_metrics[](fg:#282828 bg:#b8bb26)$character"""

[directory]
format = "[  $path ]($style)"
style = "fg:#b8bb26 bg:#282828"

[git_branch]
format = '[ $symbol$branch(:$remote_branch) ]($style)'
symbol = "  "
style = "fg:#b8bb26 bg:#282828"

[git_status]
format = '[$all_status]($style)'
style = "fg:#b8bb26 bg:#282828"

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#b8bb26 bg:#282828"
deleted_style = "fg:#b8bb26 bg:#282828"
disabled = false

[hg_branch]
format = "[ $symbol$branch ]($style)"
symbol = " "

[cmd_duration]
format = "[ 󱎫 $duration ]($style)"
style = "fg:#83a598 bg:#3c3836"

[character]
success_symbol = '[ ➜](bold #282828) '
error_symbol = '[ ✗](bold red) '

[time]
disabled = false
time_format = "%R"
style = "bg:#3c3836"
format = '[[ 󱑍 $time ](bg:#3c3836 fg:#83a598)]($style)'
