# HyprEmoji Configuration

# Keybind to open hypremoji
bind = SUPER, period, exec, hypremoji

# Window rules for HyprEmoji
windowrule = float on, match:title ^(HyprEmoji)$ 
windowrule = center on, match:title ^(HyprEmoji)$
windowrule = size 800 600, match:title ^(HyprEmoji)$
