#!/bin/bash
# Override the GTK accent/selection color to match the current YAHR theme's
# primary accent, on top of whichever static GTK theme package is active.
#
# Why this is needed: the GTK theme packages in ~/.themes (Catppuccin-Dark,
# Material-Dark-Palenight, Tokyonight-Dark, etc.) are hand-authored community
# forks with their own baked-in accent color — they don't reflect the exact
# per-theme colors used by Quickshell/Hyprland/mako/kitty. This is why
# GTK apps like Thunar visually clash with the rest of the desktop.
#
# Fix: all of these theme packages are built on the "Materia" theme
# framework and expose their accent/selection color via the standard
# @define-color theme_selected_bg_color / theme_selected_fg_color
# variables. GTK loads the user's ~/.config/gtk-3.0/gtk.css (and gtk-4.0
# equivalent) *after* the active theme's own gtk.css, so redefining these
# variables here overrides them theme-wide with zero dependency on which
# GTK theme package is currently selected.

HYPR_THEMES_DIR="$HOME/.config/hypr/themes"
CURRENT_THEME_FILE="$HOME/.config/hypr/.current-theme"
GTK3_CSS="$HOME/.config/gtk-3.0/gtk.css"
GTK4_CSS="$HOME/.config/gtk-4.0/gtk.css"

if [[ -f "$CURRENT_THEME_FILE" ]]; then
    current_theme=$(cat "$CURRENT_THEME_FILE" | tr -d '[:space:]')
    THEME_FILE="$HYPR_THEMES_DIR/${current_theme}.conf"
fi

if [[ -z "$current_theme" || ! -f "$THEME_FILE" ]]; then
    echo "Error: Could not determine current theme file"
    exit 1
fi

get_color() {
    local color_var="$1"
    grep "^$color_var" "$THEME_FILE" | sed -E 's/.*= *rgb\(([^)]+)\).*/\1/' | head -1
}

accent_hex=$(get_color '\$accent-blue')
if [[ -z "$accent_hex" ]]; then
    echo "Error: Could not read \$accent-blue from $THEME_FILE"
    exit 1
fi

# Pick a readable foreground color for text/icons drawn on top of the
# accent color, based on perceived brightness (simple luminance formula).
r=$((16#${accent_hex:0:2}))
g=$((16#${accent_hex:2:2}))
b=$((16#${accent_hex:4:2}))
luminance=$(( (299 * r + 587 * g + 114 * b) / 1000 ))
if (( luminance > 140 )); then
    fg_hex="1b1e2b"   # dark text on a bright accent
else
    fg_hex="ffffff"   # light text on a dark accent
fi

accent="#$accent_hex"
fg="#$fg_hex"

css_content="/* Auto-generated by sync-gtk-accent.sh — do not edit by hand.
   Overrides the active GTK theme's accent/selection color to match the
   current YAHR theme ($current_theme). Regenerated on every theme switch. */
@define-color theme_selected_bg_color $accent;
@define-color theme_selected_fg_color $fg;
@define-color accent_color $accent;
@define-color accent_bg_color $accent;
@define-color accent_fg_color $fg;
"

mkdir -p "$(dirname "$GTK3_CSS")" "$(dirname "$GTK4_CSS")"
echo "$css_content" > "$GTK3_CSS"
echo "$css_content" > "$GTK4_CSS"

echo "✓ GTK accent color synced to $accent (theme: $current_theme)"
