#!/bin/bash

# Sync Wofi theme with current Hyprland theme

HYPRLAND_CONF="$HOME/.config/hypr/hyprland.conf"
WOFI_STYLE="$HOME/.config/wofi/style.css"

# Get current theme from Hyprland config
THEME_FILE=$(grep "^source.*themes.*\.conf" "$HYPRLAND_CONF" | sed 's/.*= *//')

if [ -z "$THEME_FILE" ] || [ ! -f "$THEME_FILE" ]; then
    echo "Error: Could not determine theme file from Hyprland config"
    exit 1
fi

theme_name=$(basename "$THEME_FILE" .conf)

# Extract colors from Hyprland theme file
get_color() {
    local color_var="$1"
    grep "^$color_var" "$THEME_FILE" | sed -E 's/.*= *rgb\(([^)]+)\).*/\1/' | head -1
}

accent_blue=$(get_color '\$accent-blue')
fg_primary=$(get_color '\$fg-primary')
bg_base=$(get_color '\$bg-base')
surface_0=$(get_color '\$surface-0')
surface_1=$(get_color '\$surface-1')

echo "Syncing Wofi theme for: $theme_name"

# Ensure wofi directory exists
mkdir -p "$(dirname "$WOFI_STYLE")"

# Generate wofi stylesheet
cat > "$WOFI_STYLE" << EOF
/* Wofi Stylesheet - Auto-generated by theme-switcher */
/* Theme: $theme_name */

* {
    font-family: "Maple Mono", "JetBrainsMono Nerd Font", monospace;
    font-size: 14px;
}

window {
    margin: 0px;
    padding: 0px;
    border: 2px solid #$accent_blue;
    background-color: rgba(0, 0, 0, 0);
    border-radius: 12px;
    outline: none;
}

#inner-box {
    margin: 0px;
    padding: 0px;
    border: none;
    background-color: #$bg_base;
    border-radius: 10px;
}

#outer-box {
    margin: 0px;
    padding: 0px;
    border: none;
    background-color: transparent;
}

#scroll {
    margin: 0px;
    padding: 0px;
    border: none;
    background-color: transparent;
}

#input {
    margin: 12px 12px 8px 12px;
    padding: 12px 16px;
    border: 2px solid #$surface_1;
    color: #$fg_primary;
    background-color: #$surface_0;
    border-radius: 8px;
    font-size: 14px;
    outline: none;
}

#input:focus {
    border: 2px solid #$accent_blue;
    background-color: #$surface_1;
}

#text {
    margin: 0px;
    padding: 12px 16px;
    border: none;
    color: #$fg_primary;
    background-color: transparent;
} 

#entry {
    background-color: transparent;
    border: none;
    outline: none;
    margin: 2px 4px;
    padding: 0px;
    border-radius: 8px;
}

#entry:hover {
    background-color: #$surface_1;
}

#entry:hover #text {
    color: #$accent_blue;
}

#entry:selected {
    background-color: #$accent_blue;
    border: none;
    outline: none;
}

#entry:selected #text {
    color: #$bg_base;
    font-weight: 600;
}
EOF

echo "✓ Wofi theme synced"
