#!/bin/bash

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
THEME_FILE="$SCRIPT_DIR/theme.txt"

# Read current theme
if [ ! -f "$THEME_FILE" ]; then
    echo "No theme file found"
    exit 1
fi

THEME=$(cat "$THEME_FILE")

# Source theme colors
source "$SCRIPT_DIR/theme-colors.sh"

echo "🎨 Syncing Wofi theme to: $THEME"

# Define wofi style path
WOFI_STYLE="$HOME/.config/wofi/style.css"

# Ensure wofi directory exists
mkdir -p "$(dirname "$WOFI_STYLE")"

# Generate wofi stylesheet
cat > "$WOFI_STYLE" << EOF
/* Wofi Stylesheet - Auto-generated by theme-switcher */
/* Theme: $THEME */

* {
    font-family: "Maple Mono", "JetBrainsMono Nerd Font", monospace;
    font-size: 14px;
}

window {
    margin: 0px;
    padding: 0px;
    border: 2px solid $ACCENT_BLUE;
    background-color: $BG_BASE;
    border-radius: 12px;
    outline: none;
}

#input {
    margin: 12px 12px 8px 12px;
    padding: 12px 16px;
    border: 2px solid $SURFACE1;
    color: $FG_PRIMARY;
    background-color: $SURFACE0;
    border-radius: 8px;
    font-size: 14px;
    outline: none;
}

#input:focus {
    border: 2px solid $ACCENT_BLUE;
    background-color: $SURFACE1;
}

#inner-box {
    margin: 0px 8px 8px 8px;
    padding: 4px;
    border: none;
    background-color: transparent;
}

#outer-box {
    margin: 0px;
    padding: 0px;
    border: none;
    background-color: transparent;
}

#scroll {
    margin: 0px;
    padding: 0px;
    border: none;
}

#text {
    margin: 0px;
    padding: 12px 16px;
    border: none;
    color: $FG_PRIMARY;
    background-color: transparent;
} 

#entry {
    background-color: transparent;
    border: none;
    outline: none;
    margin: 2px 4px;
    padding: 0px;
    border-radius: 8px;
    transition: all 200ms ease;
}

#entry:hover {
    background-color: $SURFACE1;
}

#entry:hover #text {
    color: $ACCENT_BLUE;
}

#entry:selected {
    background-color: $ACCENT_BLUE;
    border: none;
    outline: none;
}

#entry:selected #text {
    color: $BG_BASE;
    font-weight: 600;
}
EOF

echo "✓ Wofi theme synced"
