#################
### AUTOSTART ###
#################

exec-once = quickshell
exec-once = swww-daemon
exec-once = mako
exec-once = hyprpolkitagent
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
