#################
### AUTOSTART ###
#################

exec-once = quickshell
exec-once = swww-daemon
exec-once = mako
exec-once = hypridle
exec-once = hyprpolkitagent
exec-once = wl-paste --watch cliphist store
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = ~/.config/quickshell/monitor-change-handler.sh
