################
### MONITORS ###
################

# Internal laptop display (with scale factor)
# Disabled by default to prevent mouse capture when lid is closed at boot
# Will be enabled by lid switch binding in keybinds.conf when lid opens

# Use this ONLY if you have an external monitor and want to use your laptop in clamshell mode.
# monitor=eDP-1,disable

# This is my preferred configuration for my own laptop, ignore)
# monitor=eDP-1,1920x1200@144,auto,1.2

# External monitor (modify this per your setup, or leave it commented out to use the default monitor configuration)
# monitor=HDMI-A-1,1920x1080@60,0x0,1

# Bind all workspaces to external monitor for clamshell mode
# workspace=1,monitor:HDMI-A-1
# workspace=2,monitor:HDMI-A-1
# workspace=3,monitor:HDMI-A-1
# workspace=4,monitor:HDMI-A-1
# workspace=5,monitor:HDMI-A-1
# workspace=6,monitor:HDMI-A-1
# workspace=7,monitor:HDMI-A-1
# workspace=8,monitor:HDMI-A-1
# workspace=9,monitor:HDMI-A-1
# workspace=10,monitor:HDMI-A-1

# This is the default monitor configuration. Edit or comment out if not needed.
monitor=,preferred,auto,1
