###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = thunar
$menu = ~/.config/quickshell/toggle-app-launcher
$calendar = ~/.config/quickshell/toggle-calendar
$powermenu = ~/.config/quickshell/toggle-power-menu
$themeswitcher = ~/.config/quickshell/toggle-theme-switcher
$browser = firefox
$editor = nvim
