##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Floaters
windowrule = float on, match:title ^(.*Hyprshot.*)$
windowrule = float on, match:title ^(.*Waypaper.*)$

# System Tray Helper Applications
windowrule = float on, match:class ^(org\.pulseaudio\.pavucontrol)$
windowrule = center on, match:class ^(org\.pulseaudio\.pavucontrol)$
windowrule = size 800 600, match:class ^(org\.pulseaudio\.pavucontrol)$

windowrule = float on, match:class ^(pavucontrol)$
windowrule = center on, match:class ^(pavucontrol)$
windowrule = size 800 600, match:class ^(pavucontrol)$

windowrule = float on, match:class ^(blueman-manager)$
windowrule = center on, match:class ^(blueman-manager)$
windowrule = size 800 600, match:class ^(blueman-manager)$

windowrule = float on, match:class ^(\.blueman-manager-wrapped)$
windowrule = center on, match:class ^(\.blueman-manager-wrapped)$
windowrule = size 800 600, match:class ^(\.blueman-manager-wrapped)$

windowrule = float on, match:class ^(kitty-nmtui)$
windowrule = size 800 600, match:class ^(kitty-nmtui)$
windowrule = center on, match:class ^(kitty-nmtui)$

windowrule = float on, match:class ^(xfce4-power-manager-settings)$
windowrule = center on, match:class ^(xfce4-power-manager-settings)$
windowrule = size 800 600, match:class ^(xfce4-power-manager-settings)$

# Float Rules for Pluck
windowrule = float on, match:title ^(Pluck - Color Palette Extractor)$
# windowrule = size 1000 700, match:class ^(Pluck - Color Palette Extractor)$
windowrule = center on, match:class ^(Pluck - Color Palette Extractor)$

# Fullscreen
windowrule = fullscreen on, match:class ^(feh)$

# Quickshell Calendar Widget - match all floating quickshell windows
windowrule = size 480 460, match:class ^(quickshell)$, match:float true
windowrule = move 50% 50, match:class ^(quickshell)$, match:float true
windowrule = animation slide, match:class ^(quickshell)$, match:float true

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false
