##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Floaters
windowrulev2 = float, title:^(.*Hyprshot.*)$
windowrulev2 = float, title:^(.*Waypaper.*)$

# System Tray Helper Applications
windowrulev2 = float, class:^(org\.pulseaudio\.pavucontrol)$
windowrulev2 = center, class:^(org\.pulseaudio\.pavucontrol)$
windowrulev2 = size 800 600, class:^(org\.pulseaudio\.pavucontrol)$

windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = center, class:^(pavucontrol)$
windowrulev2 = size 800 600, class:^(pavucontrol)$

windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = center, class:^(blueman-manager)$
windowrulev2 = size 800 600, class:^(blueman-manager)$

windowrulev2 = float, class:^(\.blueman-manager-wrapped)$
windowrulev2 = center, class:^(\.blueman-manager-wrapped)$
windowrulev2 = size 800 600, class:^(\.blueman-manager-wrapped)$

windowrulev2 = float, class:^(kitty-nmtui)$
windowrulev2 = size 800 600, class:^(kitty-nmtui)$
windowrulev2 = center, class:^(kitty-nmtui)$

windowrulev2 = float, class:^(xfce4-power-manager-settings)$
windowrulev2 = center, class:^(xfce4-power-manager-settings)$
windowrulev2 = size 800 600, class:^(xfce4-power-manager-settings)$

# Float Rules for Pluck
windowrulev2 = float, title:^(Pluck - Color Palette Extractor)$
# windowrulev2 = size 1000 700, class:^(Pluck - Color Palette Extractor)$
windowrulev2 = center, class:^(Pluck - Color Palette Extractor)$

# Fullscreen
windowrulev2 = fullscreen, class:^(feh)$

# Quickshell Calendar Widget - match all floating quickshell windows
windowrulev2 = size 480 460, class:^(quickshell)$, floating:1
windowrulev2 = move 50% 50, class:^(quickshell)$, floating:1
windowrulev2 = animation slide, class:^(quickshell)$, floating:1

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0
