##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Floaters
windowrulev2 = float, title:^(.*Hyprshot.*)$
windowrulev2 = float, title:^(.*Waypaper.*)$

# System Tray Helper Applications
windowrule = float,class:^(org.pulseaudio.pavucontrol)$
windowrule = center,class:^(org.pulseaudio.pavucontrol)$
windowrule = size 800 600,class:^(org.pulseaudio.pavucontrol)$

windowrule = float,class:^(pavucontrol)$
windowrule = center,class:^(pavucontrol)$
windowrule = size 800 600,class:^(pavucontrol)$

windowrule = float,class:^(blueman-manager)$
windowrule = center,class:^(blueman-manager)$
windowrule = size 800 600,class:^(blueman-manager)$

windowrule = float,class:^(.blueman-manager-wrapped)$
windowrule = center,class:^(.blueman-manager-wrapped)$
windowrule = size 800 600,class:^(.blueman-manager-wrapped)$

windowrule = float,class:^(kitty-nmtui)$
windowrule = size 800 600,class:^(kitty-nmtui)$
windowrule = center,class:^(kitty-nmtui)$

windowrule = float,class:^(xfce4-power-manager-settings)$
windowrule = center,class:^(xfce4-power-manager-settings)$
windowrule = size 800 600,class:^(xfce4-power-manager-settings)$

# Float Rules for Pluck
windowrulev2 = float, title:^(Pluck - Color Palette Extractor)$
# windowrulev2 = size 1000 700, class:^(Pluck - Color Palette Extractor)$
windowrulev2 = center, class:^(Pluck - Color Palette Extractor)$

#Fullscreen
windowrulev2 = fullscreen, class:^(feh)$

# Quickshell Calendar Widget - match all floating quickshell windows
windowrulev2 = size 480 460, class:^(quickshell)$, floating:1
windowrulev2 = move 50% 50, class:^(quickshell)$, floating:1
windowrulev2 = animation slide, class:^(quickshell)$, floating:1

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
